import type { Technique } from '../shared/catalog-types';

const sourceFile = 'teleprompter/assets/quick-snippets.md';

export const techniques: readonly Technique[] = [
  {
    id: 'surgical-edit',
    title: 'Surgical edit',
    categoryId: 'local-edits',
    summary: 'Correct one exact detail while preserving the whole image around it.',
    prompt: 'Change only [thing]. Preserve the subject identity, pose, camera, framing, lens feel, perspective, lighting, colors, scene layout, and all unaffected objects. Keep the edit local and reconstruct surrounding pixels naturally. Do not redesign or reinterpret anything else.',
    shorthandTemplate: 'fix: [exact thing]. Lock everything else.',
    shorthandEntryIds: ['route-fix', 'route-lock'],
    tags: ['local edit', 'preservation', 'repair'],
    searchTerms: ['surgical', 'correction', 'exact detail', 'fix'],
    cautionIds: ['preservation'],
    previewId: 'surgical-edit',
    order: 1,
    sources: [{ file: sourceFile, heading: '## 1. Surgical edit' }],
  },
  {
    id: 'remove-one-thing',
    title: 'Remove one thing',
    categoryId: 'local-edits',
    summary: 'Remove a named object or person and reconstruct the background cleanly.',
    prompt: 'Remove only [target] and plausibly reconstruct what should be behind it. Preserve all people, pose, camera angle, crop, lens distortion, lighting, perspective, architecture, and object positions. Do not add anything new.',
    shorthandTemplate: 'remove: [object/person/text]. Lock everything else.',
    shorthandEntryIds: ['route-remove', 'route-lock'],
    tags: ['remove', 'cleanup', 'background'],
    searchTerms: ['delete', 'reconstruct', 'object removal'],
    cautionIds: ['preservation'],
    previewId: 'remove-one-thing',
    order: 2,
    sources: [{ file: sourceFile, heading: '## 2. Remove one thing' }],
  },
  {
    id: 'multi-reference-composite',
    title: 'Multi-reference composite',
    categoryId: 'reference-transfers',
    summary: 'Assign each reference one role and transfer only those named traits.',
    prompt: 'Image 1 is the base scene. Image 2 is reference only for [role]. Image 3 is reference only for [role]. Transfer only those named traits; do not import unrelated content from the references. Preserve Image 1\'s camera, framing, lens feel, lighting, environment, perspective, scale, occlusion, and all other scene content.',
    shorthandTemplate: '1=base; 2=[role]; 3=[role]. [change].',
    shorthandEntryIds: ['pattern-reference-roles', 'route-swap'],
    tags: ['references', 'role assignment', 'composite'],
    searchTerms: ['multi-reference', 'base scene', 'transfer roles'],
    example: '1=base; 2=pose; 3=face. Put 1\'s subject in 2\'s pose with 3\'s face. Lock camera + scene.',
    cautionIds: ['reference-roles'],
    previewId: 'multi-reference-composite',
    order: 3,
    sources: [{ file: sourceFile, heading: '## 3. Multi-reference composite' }],
  },
  {
    id: 'style-tone-transfer',
    title: 'Style & tone transfer',
    categoryId: 'reference-transfers',
    summary: 'Borrow visible palette and treatment while keeping the base scene intact.',
    prompt: 'Use Image 2 only for palette, lighting, contrast, material treatment, and overall visual mood. Keep Image 1\'s subject, pose, composition, camera, scene geometry, objects, and content unchanged. Do not copy text or objects from Image 2.',
    shorthandTemplate: 'tone: match image 2 only; keep image 1 content + geometry.',
    shorthandEntryIds: ['route-style', 'route-tone'],
    tags: ['style', 'tone', 'palette'],
    searchTerms: ['mood', 'lighting transfer', 'material treatment'],
    cautionIds: ['reference-roles'],
    previewId: 'style-tone-transfer',
    order: 4,
    sources: [{ file: sourceFile, heading: '## 4. Style / tone only' }],
  },
  {
    id: 'face-identity-transfer',
    title: 'Face & identity transfer',
    categoryId: 'reference-transfers',
    summary: 'Transfer a face while preserving the base pose, wardrobe, camera, and scene.',
    prompt: 'Replace only the face/identity using Image 2. Preserve Image 1\'s exact pose, head orientation, body proportions, wardrobe, crop, camera, lens feel, lighting direction, shadows, and background. Match the new face naturally to the existing perspective and light; keep the likeness faithful.',
    shorthandTemplate: 'face: use 2. Keep 1\'s pose/camera/light.',
    shorthandEntryIds: ['route-face'],
    tags: ['face', 'identity', 'likeness'],
    searchTerms: ['facial features', 'head orientation', 'identity lock'],
    cautionIds: ['reference-roles'],
    previewId: 'face-identity-transfer',
    order: 5,
    sources: [{ file: sourceFile, heading: '## 5. Face / identity lock' }],
  },
  {
    id: 'pose-transfer',
    title: 'Pose transfer',
    categoryId: 'reference-transfers',
    summary: 'Transfer a subject pose while keeping identity, clothing, camera, and scene.',
    prompt: 'Change only the subject\'s pose to match Image 2. Preserve Image 1\'s identity, facial features, hairstyle, clothing, scene, camera, crop, lens distortion, lighting, and color. Resolve joints, hands, contact points, and weight distribution naturally.',
    shorthandTemplate: 'pose: use 2. Keep 1\'s face + scene.',
    shorthandEntryIds: ['route-pose'],
    tags: ['pose', 'anatomy', 'transfer'],
    searchTerms: ['body position', 'joints', 'weight distribution'],
    cautionIds: ['reference-roles'],
    previewId: 'pose-transfer',
    order: 6,
    sources: [{ file: sourceFile, heading: '## 6. Pose transfer' }],
  },
  {
    id: 'perspective-correction',
    title: 'Perspective correction',
    categoryId: 'camera-framing',
    summary: 'Align scene geometry to a shared vanishing-point system without moving the subject.',
    prompt: 'Correct only the scene geometry. Align [edges/desks/people/objects] to the same vanishing-point system and make repeated objects parallel in world space. Preserve camera position, lens feel, main subject, pose, lighting, crop, and styling. Keep foreground/background scale and occlusion physically coherent.',
    shorthandTemplate: 'perspective: [what should align]. Use marked guides. Lock subject.',
    shorthandEntryIds: ['route-perspective'],
    tags: ['perspective', 'vanishing point', 'geometry'],
    searchTerms: ['alignment', 'parallel', 'world space'],
    cautionIds: ['preservation', 'camera-cues'],
    previewId: 'perspective-correction',
    order: 7,
    sources: [{ file: sourceFile, heading: '## 7. Perspective / vanishing point' }],
  },
  {
    id: 'camera-lock',
    title: 'Camera lock',
    categoryId: 'camera-framing',
    summary: 'Preserve the existing camera feel while applying one named change.',
    prompt: 'Preserve the existing camera position, height, viewing direction, framing, crop, wide-angle/low-focal-length appearance, barrel/fisheye distortion, and perspective. Apply only [change]. Do not normalize the lens or recenter the composition.',
    shorthandTemplate: 'camera lock: same angle, crop, focal feel + barrel distortion. [change].',
    shorthandEntryIds: ['route-camera-lock', 'route-lock'],
    tags: ['camera', 'framing', 'lens lock'],
    searchTerms: ['barrel distortion', 'camera position', 'do not recenter'],
    cautionIds: ['preservation', 'camera-cues'],
    previewId: 'camera-lock',
    order: 8,
    sources: [{ file: sourceFile, heading: '## 8. Camera lock' }],
  },
  {
    id: 'reframe',
    title: 'Reframe',
    categoryId: 'camera-framing',
    summary: 'Adapt the aspect ratio while preserving subject scale, pose, and lens feel.',
    prompt: 'Adapt to [aspect ratio] while preserving the subject\'s identity, pose, relative scale, camera angle, lens feel, and key scene geometry. Extend/crop the environment naturally. Do not redesign the scene.',
    shorthandTemplate: 'reframe: 4:5. Keep subject scale + camera feel.',
    shorthandEntryIds: ['route-reframe'],
    tags: ['reframe', 'aspect ratio', 'crop'],
    searchTerms: ['4:5', 'extend', 'crop environment'],
    cautionIds: ['preservation', 'camera-cues'],
    previewId: 'reframe',
    order: 9,
    sources: [{ file: sourceFile, heading: '## 9. Reframe' }],
  },
  {
    id: 'clean-environment',
    title: 'Clean environment',
    categoryId: 'local-edits',
    summary: 'Remove clutter or text while keeping architecture, perspective, and negative space.',
    prompt: 'Simplify the environment by removing [items]. Preserve architecture, perspective, lighting, clean negative space, and the main subject. Reconstruct simple plausible surfaces. Do not add replacement decor, text, logos, or busy texture.',
    shorthandTemplate: 'clean: remove [clutter/text/people]. Keep architecture.',
    shorthandEntryIds: ['route-clean'],
    tags: ['cleanup', 'clutter', 'architecture'],
    searchTerms: ['remove text', 'simplify', 'negative space'],
    cautionIds: ['preservation'],
    previewId: 'clean-environment',
    order: 10,
    sources: [{ file: sourceFile, heading: '## 10. Clean environment' }],
  },
  {
    id: 'product-fidelity',
    title: 'Product fidelity',
    categoryId: 'reference-transfers',
    summary: 'Integrate a reference product while preserving its package geometry and branding.',
    prompt: 'Use Image 2 only as the product reference. Preserve its recognizable silhouette, proportions, package geometry, label placement, brand marks, and dominant colors. Integrate it into Image 1 with correct perspective, scale, grip/contact, lighting, reflections, and shadows. Preserve everything else in Image 1.',
    shorthandTemplate: 'product: match image 2 exactly; integrate into image 1.',
    shorthandEntryIds: ['route-product'],
    tags: ['product', 'packaging', 'brand'],
    searchTerms: ['label', 'silhouette', 'package geometry'],
    cautionIds: ['reference-roles'],
    previewId: 'product-fidelity',
    order: 11,
    sources: [{ file: sourceFile, heading: '## 11. Brand / product fidelity' }],
  },
  {
    id: 'controlled-motion',
    title: 'Controlled motion',
    categoryId: 'motion',
    summary: 'Add directional motion cues while keeping face, hands, and body readable.',
    prompt: 'Add subtle, swift afterimages and directional motion blur only along [motion path]. Keep the primary face, eyes, hands, and body readable and anatomically coherent. No grain, whole-frame blur, duplicated anatomy, face smearing, or noisy trails.',
    shorthandTemplate: 'motion: light afterimages along [path]; face stays clean.',
    shorthandEntryIds: ['route-motion'],
    tags: ['motion', 'afterimage', 'blur'],
    searchTerms: ['movement', 'directional blur', 'anatomy'],
    cautionIds: ['preservation'],
    previewId: 'controlled-motion',
    order: 12,
    sources: [{ file: sourceFile, heading: '## 12. Controlled motion' }],
  },
  {
    id: 'quality-restoration',
    title: 'Quality restoration',
    categoryId: 'finish-quality',
    summary: 'Clean accumulated degradation while preserving the exact image content and layout.',
    prompt: 'Quality-restoration pass only. Do not redesign, restyle, recompose, or change content. Preserve the current image\'s exact subject identity, facial likeness, pose, camera angle, framing, lens distortion, perspective, object geometry, architecture, lighting direction, exposure, color balance, and scene layout. Remove electronic noise, coarse grain, compression-like artifacts, AI smearing, muddy textures, doubled edges, malformed microdetails, and accumulated generative degradation. Restore clean natural edges, coherent fine detail, smooth clean surfaces, accurate anatomy, and realistic material definition. Keep detail restrained and photographic: no oversharpening halos, HDR look, plastic skin, invented texture, extra objects, extra text, or altered branding. The result should look like a cleaner, higher-fidelity version of the same image, not a new interpretation.',
    shorthandTemplate: 'hq: restoration only. No redesign.',
    shorthandEntryIds: ['route-hq'],
    tags: ['restoration', 'quality', 'degradation'],
    searchTerms: ['oversharpening', 'noise', 'compression', 'artifacts'],
    cautionIds: ['preservation', 'restoration', 'render-size'],
    previewId: 'quality-restoration',
    order: 13,
    sources: [{ file: sourceFile, heading: '## 13. HIGH-QUALITY RESTORATION / ANTI-DEGRADATION' }],
  },
  {
    id: 'clean-commercial',
    title: 'Clean commercial photography',
    categoryId: 'finish-quality',
    summary: 'Set a bright, polished white-blue commercial treatment without visual clutter.',
    prompt: 'Photorealistic high-key commercial photography. Bright white and clean blue environment, cool natural daylight, airy minimal architecture, simple smooth surfaces, restrained texture, crisp believable detail, polished but not over-retouched. No film grain, electronic noise, dirty texture, heavy HDR, moody cinematic grading, or visual clutter.',
    shorthandTemplate: 'look: high-key clean commercial; white-blue daylight; minimal surfaces; no grain.',
    shorthandEntryIds: ['look-commercial', 'look-cleanblue', 'lighting-highkey'],
    tags: ['commercial', 'clean blue', 'high-key'],
    searchTerms: ['white-blue', 'daylight', 'minimal surfaces'],
    cautionIds: ['preservation'],
    previewId: 'clean-commercial',
    order: 14,
    sources: [{ file: sourceFile, heading: '## 14. Clean commercial look' }],
  },
  {
    id: 'markup-directed-edit',
    title: 'Markup-directed edit',
    categoryId: 'local-edits',
    summary: 'Use a marked region or guide as authoritative placement while protecting everything else.',
    prompt: 'Apply the requested change only in the marked/identified region. Treat the red line/coordinate as authoritative placement or geometry guidance. Preserve all unmarked regions, including camera, identity, lighting, composition, perspective, and surrounding objects.',
    shorthandTemplate: 'marked area only: [change]. Treat red guide as geometry.',
    shorthandEntryIds: ['pattern-marked-area', 'route-fix'],
    tags: ['markup', 'coordinates', 'guided edit'],
    searchTerms: ['red guide', 'marked area', 'geometry'],
    cautionIds: ['preservation'],
    previewId: 'markup-directed-edit',
    order: 15,
    sources: [{ file: sourceFile, heading: '## 15. Red markup / coordinate edit' }],
  },
];
